import img1 from "../assets/images/1.jpg"
import img2 from "../assets/images/146d8456038a52d66db6b85812001629.png"
import img3 from "../assets/images/148_75703840_1.jpg"
import img4 from "../assets/images/2.png"
import img5 from "../assets/images/202036_1659896601.webp"
import img6 from "../assets/images/24a3330eff4369efbb8f1bba46004c4a.png"
import img7 from "../assets/images/254dd900deb2dcab9d9bcd8d6776f5bc.jpg"
import img8 from "../assets/images/27382eba295b434d4ea88ac658fca9e4.jpg"
import img9 from "../assets/images/3.png"
import img10 from "../assets/images/4.png"
import img11 from '../assets/images/5.png'
import img12 from '../assets/images/6.png'
import img13 from '../assets/images/7.png'
import img14 from '../assets/images/837b18453a99449eb28061f0cf884aa8.png'
import img15 from '../assets/images/ab584ce252c38550bbe229728f3cae9f.png'
import img16 from '../assets/images/Asad-Lattafa-Perfume-Skit-Store.webp'
import img17 from '../assets/images/burberry-weekend-women-edp-100ml-perfume-philippines-best-price.jpg'
import img18 from '../assets/images/c8145f2b7df9c2ec4c039cd5c4ac27c3.png'
import img19 from '../assets/images/d196981c714866bdaabd4a0c60483e97.png'
import img20 from '../assets/images/d252dcfaa6adea82c5762e035b318808.png'
import img111 from '../assets/images/img111.png'
import img112 from '../assets/images/img112.png'
import img112 from '../assets/images/img112.png'


export const data=[
        {
          _id: 1,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Addidas',
          image: img1,
          fragrance_type: 'Perfume',
          scent_type: 'fresh',
          priceCents: 6600000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 2,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'female',
          brand: 'Hugo boss',
          image: img2,
          fragrance_type: 'Perfume',
          scent_type: 'Cedar',
          priceCents: 9700000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 3,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Armani',
          image: img3,
          fragrance_type: 'Perfume',
          scent_type: 'Citirus',
          priceCents: 2400000,
          size: 2.3,
          availability: false,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 4,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'female',
          brand: 'adidas',
          image: img4,
          fragrance_type: 'Perfume',
          scent_type: 'Floral',
          priceCents: 7600000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 5,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Dior',
          image: img5,
          fragrance_type: 'Perfume',
          scent_type: 'Rose',
          priceCents: 1600000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 6,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'female',
          brand: 'Vitton',
          image: img6,
          fragrance_type: 'Eau De Parfum',
          scent_type: 'Lemon',
          priceCents: 4600000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 7,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Giorgio Armani',
          image: img7,
          fragrance_type: 'Eau De Parfum',
          scent_type: 'Vanilla',
          priceCents: 1560000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: true,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 8,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Ralph Lauren',
          image: img8,
          fragrance_type: 'Eau De Parfum',
          scent_type: 'Mush.Amber',
          priceCents: 8600000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: true,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 9,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Mont Blanc',
          image: img9,
          fragrance_type: 'Eau De Cologne',
          scent_type: 'Mush.Amber',
          priceCents: 6600000,
          size: 2.3,
          availability: false,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 10,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'female',
          brand: 'Lataffa',
          image: img10,
          fragrance_type: 'Eau De Cologne',
          scent_type: 'Mush.Amber',
          priceCents: 9600000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 11,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'female',
          brand: 'Versace',
          image: img11,
          fragrance_type: 'Eau De Cologne',
          scent_type: 'fresh',
          priceCents: 2200000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 12,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Zaien',
          image: img12,
          fragrance_type: 'Eau De Parfum',
          scent_type: 'Vanilla',
          priceCents: 2300000,
          size: 2.3,
          availability: false,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 13,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Jimmmy Choo',
          image: img13,
          fragrance_type: 'Perfume oil',
          scent_type: 'Vanilla',
          priceCents: 6700000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: true,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 14,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Dolce & Gabbana',
          image: img14,
          fragrance_type: 'Deodorant',
          scent_type: 'Lemon',
          priceCents: 7800000,
          size: 2.3,
          availability: false,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: true,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 15,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'female',
          brand: 'Dior',
          image: img15,
          fragrance_type: 'Perfume',
          scent_type: 'Lemon',
          priceCents: 1000000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: true,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 16,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Armani',
          image: img16,
          fragrance_type: 'Perfume',
          scent_type: 'Lemon',
          priceCents: 4900000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 17,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Armaf',
          image: img17,
          fragrance_type: 'Body Spray',
          scent_type: 'Rose',
          priceCents: 9000000,
          size: 2.3,
          availability: false,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: true,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 18,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Calvin klein',
          image: img18,
          fragrance_type: 'Body Spray',
          scent_type: 'Rose',
          priceCents: 2300000,
          size: 2.3,
          availability: false,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 19,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'female',
          brand: 'Essenza',
          image: img19,
          fragrance_type: 'Perfume',
          scent_type: 'Rose',
          priceCents: 6700000,
          size: 2.3,
          availability: true,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },
        {
          _id: 20,
          name: 'maison francis kurkdjian paris',
          description: 'Lorem ipsum dolor sit amet hfghgbdyddvh',
          gender: 'male',
          brand: 'Hugo boss',
          image: img20,
          fragrance_type: 'Body Spray',
          scent_type: 'fresh',
          priceCents: 1300000,
          size: 2.3,
          availability: false,
          about: 'The Maison Francis Kurkdjian collection is sketched like a fragrance wardrobe, with myriad of facets of emotions. Designed in the tradition of luxury French perfumery, it advocates nevertheless a contemporary vision of the art of creating and wearing perfume.',
          scent_profile: 'Maison Francis Kurkdjian is often described as a warm, rich, and sophisticated fragrance. It typically features notes of amber, vanilla, benzoin, and tonka bean, creating a harmonious blend that exudes elegance and sensuality.',
          usage: 'For long-lasting fragrance that you can carry throughout the day and to minimize the need for reapplying, focus on your pulse points behind your ears, at the base of your neck and on your wrists as well as warmer areas of the body, such as behind the knees and inside the elbow. These are the best places to apply your fragrance since the scent intensifies by the warmth of your body.',
          refund_policy: 'NO REFUND',
          isnew: false,
          imageUrl: {
            1: img111,
            2: img112,
            3: img112,
          }
        },

]